# lifecycle policy
PUT _ilm/policy/rotate-palo-logs
{
  "policy": {
    "phases": {
      "delete": {
        "min_age": "14d",
        "actions": {
          "delete": {
            "delete_searchable_snapshot": true
          }
        }
      },
      "cold": {
        "min_age": "1d",
        "actions": {
          "set_priority": {
            "priority": 0
          }
        }
      },
      "warm": {
        "min_age": "1h",
        "actions": {
          "set_priority": {
            "priority": 50
          }
        }
      },
      "hot": {
        "min_age": "0ms",
        "actions": {
          "rollover": {
            "max_age": "30d",
            "max_primary_shard_size": "50gb"
          },
          "set_priority": {
            "priority": 100
          }
        }
      }
    }
  }
}

# index template
PUT _index_template/palo-logs
{
  "index_patterns": [
    "fluentd_stream*"
  ],
  "template": {
    "settings": {
      "index": {
        "lifecycle": {
          "name": "rotate-palo-logs"
        },
        "number_of_shards": "1",
        "number_of_replicas": "1"
      }
    }
  },
  "composed_of": [],
  "data_stream": {
    "hidden": false,
    "allow_custom_routing": false
  }
}

# create data stream
DELETE fluentd_stream
PUT _data_stream/fluentd_stream

# Create Kibana data view
curl -X POST -u <username:password> -H 'kbn-xsrf: true' -H 'Content-Type: application/json' http://<kibana-host>:5601/api/data_views/data_view -d '
{
    "data_view": {
        "title": "fluentd_stream",
        "name": "Palo Logs",
        "timeFieldName": "High Resolution Timestamp"
    }
}'
